{ config, pkgs, lib, ... }:
let
  waterfoxProfileName = "yza1eyzc.default-release";
  waterfoxProfileRel = ".var/app/net.waterfox.waterfox/.waterfox/${waterfoxProfileName}";

  protonPassExtId = "78272b6fa58f4a1abaac99321d503a20@proton.me";
  darkReaderExtId = "addon@darkreader.org";
  vimiumExtId = "{d7742d87-e61d-4b78-b8a1-b469842139fa}";

  protonPassAddon = pkgs.fetchFirefoxAddon {
    name = "proton-pass";
    url = "https://addons.mozilla.org/firefox/downloads/file/4686427/proton_pass-1.34.2.xpi";
    sha256 = "0yzakqii8cp557naz65nnp3la378xn1zqw69b5abkb55pjdvbd03";
    fixedExtid = protonPassExtId;
  };

  darkReaderAddon = pkgs.fetchFirefoxAddon {
    name = "dark-reader";
    url = "https://addons.mozilla.org/firefox/downloads/file/4710145/darkreader-4.9.123.xpi";
    sha256 = "0hq2wjqk0azdi7nvs8r6xc0avvdg2qn56r0jv1xja81zqpd6qgls";
    fixedExtid = darkReaderExtId;
  };

  vimiumAddon = pkgs.fetchFirefoxAddon {
    name = "vimium";
    url = "https://addons.mozilla.org/firefox/downloads/file/4717567/vimium_ff-2.4.2.xpi";
    sha256 = "15nixab67dxah8kzqhdl8yn9yh31kqaq35xib89fjyhfb1kjl7hk";
    fixedExtid = vimiumExtId;
  };

  waterfoxUserJs = pkgs.writeText "waterfox-user.js" ''
    // Generated by Home Manager.
    user_pref("browser.urlbar.placeholderName", "Google");
    user_pref("extensions.autoDisableScopes", 0);
  '';

  waterfoxSearch = pkgs.runCommand "waterfox-search.json.mozlz4"
    {
      nativeBuildInputs = with pkgs; [
        mozlz4a
        openssl
      ];
      json = builtins.toJSON {
        version = 12;
        engines = [
          {
            id = "google";
            _isAppProvided = true;
            _metaData = {
              order = 0;
            };
          }
        ];
        metaData = {
          defaultEngineId = "google";
          defaultEngineIdHash = "@hash@";
          useSavedOrder = true;
        };
      };
      salt = ''
        ${waterfoxProfileName}googleBy modifying this file, I agree that I am doing so only within Waterfox itself, using official, user-driven search engine selection processes, and in a way which does not circumvent user consent. I acknowledge that any attempt to change this file from outside of Waterfox is a malicious act, and will be responded to accordingly.
      '';
    }
    ''
      hash="$(printf '%s' "$salt" | openssl dgst -sha256 -binary | base64 -w0)"
      json_text="$json"
      json_text="''${json_text//@hash@/$hash}"
      printf '%s' "$json_text" > search.json
      mozlz4a search.json "$out"
    '';
in
{
  home.stateVersion = "25.05";
  home.enableNixpkgsReleaseCheck = false;

  home.sessionPath = [
    "$HOME/.bun/bin"
    "$HOME/.local/bin"
    "$HOME/bin"
    "$HOME/.cargo/bin"
    "$HOME/go/bin"
    "$HOME/.npm-global/bin"
    "$HOME/.deno/bin"
    "$HOME/.local/share/pnpm"
    "$HOME/.nimble/bin"
  ];

  home.packages = with pkgs; [
    neovim
    bun
    nordic
    git
    ghostty
    grim
    slurp
    swaybg
    swayidle
    swaylock
    wl-clipboard
    wofi
    nerd-fonts.jetbrains-mono
  ];

  fonts.fontconfig.enable = true;

  gtk = {
    enable = true;
    theme = {
      name = "Nordic";
      package = pkgs.nordic;
    };
  };

  xdg.configFile."ghostty/config".text = ''
    theme = Nord
    font-family = JetBrainsMono Nerd Font
    font-size = 13
    background-opacity = 0.94
    window-padding-x = 10
    window-padding-y = 10
    gtk-titlebar = false
    shell-integration = detect
    copy-on-select = clipboard
    confirm-close-surface = false
  '';

  programs.ssh = {
    enable = true;
    matchBlocks."github.com" = {
      hostname = "github.com";
      user = "git";
      identityFile = "~/.ssh/id_ed25519";
      identitiesOnly = true;
    };
  };

  home.activation.sshConfig = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
    if [ -L "$HOME/.ssh/config" ]; then
      target="$(readlink -f "$HOME/.ssh/config")"
      rm -f "$HOME/.ssh/config"
      cp "$target" "$HOME/.ssh/config"
    fi
    chmod 600 "$HOME/.ssh/config"
  '';

  home.activation.waterfoxProfile = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    profile_dir="$HOME/${waterfoxProfileRel}"
    mkdir -p "$profile_dir/extensions"

    install -m 0644 ${waterfoxUserJs} "$profile_dir/user.js"
    install -m 0644 ${waterfoxSearch} "$profile_dir/search.json.mozlz4"
    install -m 0644 ${protonPassAddon}/${protonPassExtId}.xpi "$profile_dir/extensions/${protonPassExtId}.xpi"
    install -m 0644 ${darkReaderAddon}/${darkReaderExtId}.xpi "$profile_dir/extensions/${darkReaderExtId}.xpi"
    install -m 0644 ${vimiumAddon}/${vimiumExtId}.xpi "$profile_dir/extensions/${vimiumExtId}.xpi"
  '';

  programs.swaylock.enable = true;
  programs.wofi.enable = true;
  programs.waybar = {
    enable = true;
    settings = [
      {
        layer = "top";
        position = "top";
        modules-left = [ "sway/workspaces" "sway/mode" ];
        modules-center = [ "sway/window" ];
        modules-right = [ "pulseaudio" "network" "clock" "tray" ];

        "sway/workspaces" = {
          disable-scroll = true;
          all-outputs = true;
          format = "{icon}";
          format-icons = {
            "1" = "";
            "2" = "";
            "3" = "";
            "4" = "󰎆";
            "5" = "";
            urgent = "";
            default = "";
          };
          persistent-workspaces = {
            "1" = [];
            "2" = [];
            "3" = [];
            "4" = [];
            "5" = [];
          };
        };

        clock = {
          format = "{:%a %b %d  %H:%M}";
          tooltip-format = "{:%Y-%m-%d}";
        };

        network = {
          format-wifi = "  {signalStrength}%";
          format-ethernet = "󰈀";
          format-disconnected = "󰖪";
        };

        pulseaudio = {
          format = "{icon} {volume}%";
          format-muted = "󰖁";
          format-icons = {
            default = [ "󰕿" "󰖀" "󰕾" ];
          };
        };
      }
    ];

    style = ''
      * {
        font-family: "JetBrainsMono Nerd Font", "Symbols Nerd Font";
        font-size: 13px;
      }

      window#waybar {
        background: rgba(46, 52, 64, 0.94);
        color: #eceff4;
      }

      #workspaces {
        margin: 0 8px;
      }

      #workspaces button {
        padding: 0 10px;
        color: #88c0d0;
      }

      #workspaces button.focused {
        background: #5e81ac;
        color: #eceff4;
      }

      #window,
      #clock,
      #network,
      #pulseaudio,
      #tray {
        padding: 0 12px;
      }
    '';
  };

  services.mako = {
    enable = true;
    settings = {
      background-color = "#2E3440";
      border-color = "#88C0D0";
      text-color = "#ECEFF4";
      default-timeout = 5000;
    };
  };

  services.fusuma = {
    enable = true;
    extraPackages = with pkgs; [ coreutils sway ];
    settings = {
      threshold = {
        swipe = 0.2;
      };
      interval = {
        swipe = 0.8;
      };
      swipe = {
        "3" = {
          left.command = "${pkgs.sway}/bin/swaymsg workspace next_on_output";
          right.command = "${pkgs.sway}/bin/swaymsg workspace prev_on_output";
        };
      };
    };
  };

  services.swayidle = {
    enable = true;
    systemdTarget = "sway-session.target";
    timeouts = [
      {
        timeout = 600;
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
      {
        timeout = 900;
        command = "${pkgs.systemd}/bin/systemctl suspend";
      }
    ];
    events = [
      {
        event = "before-sleep";
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
      {
        event = "lock";
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
    ];
  };

  wayland.windowManager.sway = let
    defaultGap = 12;
  in {
    enable = true;
    systemd.enable = true;
    wrapperFeatures.gtk = true;
    extraConfig = ''
      gaps inner ${toString defaultGap}
    '';

    config = {
      workspaceAutoBackAndForth = true;
      modifier = "Mod4";
      terminal = "ghostty";
      menu = "wofi --show drun";
      input = {
        "type:touchpad" = {
          tap = "enabled";
          natural_scroll = "enabled";
          scroll_method = "two_finger";
          click_method = "clickfinger";
          dwt = "enabled";
        };
      };

      bars = [
        {
          command = "waybar";
        }
      ];

      keybindings = let
        modifier = config.wayland.windowManager.sway.config.modifier;
        workspaceBindings = lib.listToAttrs (
          builtins.concatLists (map
            (n: [
              {
                name = "${modifier}+${toString n}";
                value = "workspace number ${toString n}";
              }
              {
                name = "${modifier}+Shift+${toString n}";
                value = "move container to workspace number ${toString n}";
              }
            ])
            [ 1 2 3 4 5 6 7 8 9 ])
        );
      in workspaceBindings // {
        "${modifier}+0" = "workspace number 10";
        "${modifier}+Return" = "exec ghostty";
        "${modifier}+a" = "focus parent";
        "${modifier}+b" = "splith";
        "${modifier}+d" = "exec wofi --show drun";
        "${modifier}+e" = "layout toggle split";
        "${modifier}+f" = "fullscreen toggle";
        "${modifier}+q" = "kill";
        "${modifier}+r" = "mode resize";
        "${modifier}+s" = "layout stacking";
        "${modifier}+space" = "focus mode_toggle";
        "${modifier}+h" = "focus left";
        "${modifier}+j" = "focus down";
        "${modifier}+k" = "focus up";
        "${modifier}+l" = "focus right";
        "${modifier}+Left" = "focus left";
        "${modifier}+Down" = "focus down";
        "${modifier}+Up" = "focus up";
        "${modifier}+Right" = "focus right";
        "${modifier}+Ctrl+equal" = "gaps inner current plus 5";
        "${modifier}+minus" = "scratchpad show";
        "${modifier}+Ctrl+minus" = "gaps inner current minus 5";
        "${modifier}+v" = "splitv";
        "${modifier}+w" = "layout tabbed";
        "${modifier}+Shift+equal" = "gaps inner all set ${toString defaultGap}";
        "${modifier}+Shift+minus" = "move scratchpad";
        "${modifier}+Shift+underscore" = "move scratchpad";
        "${modifier}+Ctrl+h" = "resize shrink width 10 px";
        "${modifier}+Ctrl+j" = "resize grow height 10 px";
        "${modifier}+Ctrl+k" = "resize shrink height 10 px";
        "${modifier}+Ctrl+l" = "resize grow width 10 px";
        "${modifier}+Tab" = "workspace back_and_forth";
        "${modifier}+Shift+0" = "move container to workspace number 10";
        "${modifier}+Shift+c" = "reload";
        "${modifier}+Shift+e" = "exec swaynag -t warning -m 'Exit Sway?' -B 'Yes' 'swaymsg exit'";
        "${modifier}+Shift+h" = "move left";
        "${modifier}+Shift+j" = "move down";
        "${modifier}+Shift+k" = "move up";
        "${modifier}+Shift+l" = "move right";
        "${modifier}+Shift+Left" = "move left";
        "${modifier}+Shift+Down" = "move down";
        "${modifier}+Shift+Up" = "move up";
        "${modifier}+Shift+Right" = "move right";
        "${modifier}+Shift+BackSpace" = "move scratchpad";
        "${modifier}+Shift+r" = "restart";
        "${modifier}+Shift+space" = "floating toggle";
        "Print" = "exec grim -g \"$(slurp)\" - | wl-copy";
      };

      modes.resize = {
        Escape = "mode default";
        Return = "mode default";
        h = "resize shrink width 10 px";
        j = "resize grow height 10 px";
        k = "resize shrink height 10 px";
        l = "resize grow width 10 px";
        Left = "resize shrink width 10 px";
        Down = "resize grow height 10 px";
        Up = "resize shrink height 10 px";
        Right = "resize grow width 10 px";
      };

      startup = [
        { command = "mako"; }
      ];
    };
  };
}
