{ config, pkgs, lib, osConfig, ... }:
let
  isLaptop = osConfig.networking.hostName == "nixos";
  nimbleLatest = pkgs.nimble.overrideAttrs (_: {
    version = "0.22.3";
    src = pkgs.fetchFromGitHub {
      owner = "nim-lang";
      repo = "nimble";
      rev = "v0.22.3";
      hash = "sha256-v0RhIx6ithFJqH6ThKpyvC0JB3CBCevahhCossC+deA=";
      fetchSubmodules = true;
    };
  });
  waterfoxProfileName = "yza1eyzc.default-release";
  waterfoxProfileRel = ".var/app/net.waterfox.waterfox/.waterfox/${waterfoxProfileName}";
  wallpaperDir = "${config.home.homeDirectory}/Pictures/Wallpapers";
  awwwSrc = pkgs.fetchgit {
    url = "https://codeberg.org/LGFae/awww.git";
    rev = "7a8fc2e646b97e5ae508a44d3449e3b41345d456";
    sha256 = "1vnpk8iscg1kz31jazy2zjq74fj66s82f02c0hi5afclzf0vxwvf";
  };
  awwwPackage = (import "${awwwSrc}/default.nix").packages.${pkgs.stdenv.hostPlatform.system}.awww;
  protonRcloneRemote = "proton";
  protonRcloneRemotePath = "Media";
  protonSyncLocalDir = "${config.home.homeDirectory}/.drive";
  protonRcloneSync = pkgs.writeShellScriptBin "proton-rclone-sync" ''
    set -eu

    remote="${protonRcloneRemote}:${protonRcloneRemotePath}"
    local_dir=${lib.escapeShellArg protonSyncLocalDir}
    state_dir="''${XDG_STATE_HOME:-$HOME/.local/state}/rclone-bisync/proton"
    first_run_marker="$state_dir/first-run-complete"
    rclone_config="''${RCLONE_CONFIG:-$HOME/.config/rclone/rclone.conf}"

    ${pkgs.coreutils}/bin/mkdir -p "$local_dir" "$state_dir"

    if [ ! -f "$rclone_config" ]; then
      echo "rclone config not found at $rclone_config" >&2
      echo "Run: rclone config" >&2
      exit 1
    fi

    ${pkgs.rclone}/bin/rclone mkdir "$remote"

    if [ ! -f "$first_run_marker" ]; then
      ${pkgs.rclone}/bin/rclone bisync "$local_dir" "$remote" \
        --resync \
        --create-empty-src-dirs \
        --resilient \
        --recover
      ${pkgs.coreutils}/bin/touch "$first_run_marker"
      exit 0
    fi

    exec ${pkgs.rclone}/bin/rclone bisync "$local_dir" "$remote" \
      --create-empty-src-dirs \
      --resilient \
      --recover
  '';

  protonPassExtId = "78272b6fa58f4a1abaac99321d503a20@proton.me";
  darkReaderExtId = "addon@darkreader.org";
  vimiumExtId = "{d7742d87-e61d-4b78-b8a1-b469842139fa}";

  protonPassAddon = pkgs.fetchFirefoxAddon {
    name = "proton-pass";
    url = "https://addons.mozilla.org/firefox/downloads/file/4686427/proton_pass-1.34.2.xpi";
    sha256 = "0yzakqii8cp557naz65nnp3la378xn1zqw69b5abkb55pjdvbd03";
    fixedExtid = protonPassExtId;
  };

  darkReaderAddon = pkgs.fetchFirefoxAddon {
    name = "dark-reader";
    url = "https://addons.mozilla.org/firefox/downloads/file/4710145/darkreader-4.9.123.xpi";
    sha256 = "0hq2wjqk0azdi7nvs8r6xc0avvdg2qn56r0jv1xja81zqpd6qgls";
    fixedExtid = darkReaderExtId;
  };

  vimiumAddon = pkgs.fetchFirefoxAddon {
    name = "vimium";
    url = "https://addons.mozilla.org/firefox/downloads/file/4717567/vimium_ff-2.4.2.xpi";
    sha256 = "15nixab67dxah8kzqhdl8yn9yh31kqaq35xib89fjyhfb1kjl7hk";
    fixedExtid = vimiumExtId;
  };

  waterfoxUserJs = pkgs.writeText "waterfox-user.js" ''
    // Generated by Home Manager.
    user_pref("browser.urlbar.placeholderName", "Google");
    user_pref("extensions.autoDisableScopes", 0);
  '';

  waterfoxSearch = pkgs.runCommand "waterfox-search.json.mozlz4"
    {
      nativeBuildInputs = with pkgs; [
        mozlz4a
        openssl
      ];
      json = builtins.toJSON {
        version = 12;
        engines = [
          {
            id = "google";
            _isAppProvided = true;
            _metaData = {
              order = 0;
            };
          }
        ];
        metaData = {
          defaultEngineId = "google";
          defaultEngineIdHash = "@hash@";
          useSavedOrder = true;
        };
      };
      salt = ''
        ${waterfoxProfileName}googleBy modifying this file, I agree that I am doing so only within Waterfox itself, using official, user-driven search engine selection processes, and in a way which does not circumvent user consent. I acknowledge that any attempt to change this file from outside of Waterfox is a malicious act, and will be responded to accordingly.
      '';
    }
    ''
      hash="$(printf '%s' "$salt" | openssl dgst -sha256 -binary | base64 -w0)"
      json_text="$json"
      json_text="''${json_text//@hash@/$hash}"
      printf '%s' "$json_text" > search.json
      mozlz4a search.json "$out"
    '';

  setWallpaper = pkgs.writeShellScriptBin "set-wallpaper" ''
    dir=${lib.escapeShellArg wallpaperDir}

    if [ ! -d "$dir" ]; then
      exit 0
    fi

    image="$(${pkgs.findutils}/bin/find "$dir" -maxdepth 1 -type f \
      \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) \
      | ${pkgs.coreutils}/bin/shuf -n 1)"

    if [ -z "$image" ]; then
      exit 0
    fi

    export AWWW_TRANSITION_FPS="60"
    export AWWW_TRANSITION_STEP="2"

    ${awwwPackage}/bin/awww img --resize=crop "$image"
  '';

  brightnessDown = pkgs.writeShellScriptBin "waybar-brightness-down" ''
    max="$(${pkgs.brightnessctl}/bin/brightnessctl m)"
    min="$(( (max + 9) / 10 ))"

    exec ${pkgs.brightnessctl}/bin/brightnessctl --min-value="$min" set 1%-
  '';
in
{
  imports = [
    ./modules/emacs.nix
    ./modules/fish.nix
    ./modules/neovim.nix
    ./modules/zellij.nix
    (import ./modules/sway.nix { inherit setWallpaper; })
  ];

  home.stateVersion = "25.05";
  home.enableNixpkgsReleaseCheck = false;

  programs.vscode = {
    enable = true;
    package = pkgs.vscode;
    mutableExtensionsDir = true;
  };

  programs.yazi = {
    enable = true;
    enableFishIntegration = true;
    shellWrapperName = "yy";
    settings = {
      manager = {
        show_hidden = false;
        sort_by = "natural";
        sort_dir_first = true;
      };
    };
    theme = {
      manager = {
        cwd = { bg = "#000000"; };
        hovered = { bg = "#000000"; };
        preview_hovered = { bg = "#000000"; };
        find_keyword = { bg = "#000000"; };
        find_position = { bg = "#000000"; };
      };
      tabs = {
        active = { bg = "#000000"; };
        inactive = { bg = "#000000"; };
      };
      mode = {
        normal_main = { bg = "#000000"; };
        normal_alt = { bg = "#000000"; };
        select_main = { bg = "#000000"; };
        select_alt = { bg = "#000000"; };
        unset_main = { bg = "#000000"; };
        unset_alt = { bg = "#000000"; };
      };
      status = {
        overall = { bg = "#000000"; };
        sep_left = {
          open = "";
          close = "";
        };
        sep_right = {
          open = "";
          close = "";
        };
      };
    };
  };

  programs.nix-your-shell = {
    enable = true;
    enableFishIntegration = true;
  };

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "dark-reader"
      "discord"
      "proton-pass"
      "vscode"
      "vimium"
    ];

  home.sessionPath = [
    "/etc/nixos/scripts"
    "$HOME/.bun/bin"
    "$HOME/.local/bin"
    "$HOME/bin"
    "$HOME/.cargo/bin"
    "$HOME/go/bin"
    "$HOME/.npm-global/bin"
    "$HOME/.deno/bin"
    "$HOME/.local/share/pnpm"
    "$HOME/.nimble/bin"
  ];

  home.packages = with pkgs; [
    bun
    brightnessctl
    discord
    nim-unwrapped
    nimbleLatest
    jq
    nordic
    opencode
    git
    gh
    ghostty
    grim
    slurp
    swaybg
    swayidle
    swaylock
    awwwPackage
    rclone
    protonRcloneSync
    setWallpaper
    wl-clipboard
    rofi
    termusic
    beets
    winboat
    yt-dlp
    nerd-fonts.jetbrains-mono
  ];

  fonts.fontconfig.enable = true;

  gtk = {
    enable = true;
    theme = {
      name = "Nordic";
      package = pkgs.nordic;
    };
  };

  xdg.configFile."ghostty/config".text = ''
    theme = Nord
    font-family = JetBrainsMono Nerd Font
    font-size = 13
    background = #000000
    background-opacity = 0.85
    window-padding-x = 0
    window-padding-y = 0
    gtk-titlebar = false
    shell-integration = detect
    copy-on-select = clipboard
    confirm-close-surface = false
  '';

  programs.ssh = {
    enable = true;
    matchBlocks."github.com" = {
      hostname = "github.com";
      user = "git";
      identityFile = "~/.ssh/id_ed25519";
      identitiesOnly = true;
    };
  };

  home.activation.sshConfig = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
    if [ -L "$HOME/.ssh/config" ]; then
      target="$(readlink -f "$HOME/.ssh/config")"
      rm -f "$HOME/.ssh/config"
      cp "$target" "$HOME/.ssh/config"
    fi
    chmod 600 "$HOME/.ssh/config"
  '';

  home.activation.waterfoxProfile = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    profile_dir="$HOME/${waterfoxProfileRel}"
    mkdir -p "$profile_dir/extensions"

    install -m 0644 ${waterfoxUserJs} "$profile_dir/user.js"
    install -m 0644 ${waterfoxSearch} "$profile_dir/search.json.mozlz4"
    install -m 0644 ${protonPassAddon}/${protonPassExtId}.xpi "$profile_dir/extensions/${protonPassExtId}.xpi"
    install -m 0644 ${darkReaderAddon}/${darkReaderExtId}.xpi "$profile_dir/extensions/${darkReaderExtId}.xpi"
    install -m 0644 ${vimiumAddon}/${vimiumExtId}.xpi "$profile_dir/extensions/${vimiumExtId}.xpi"
  '';

  home.activation.wallpaperDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/Pictures/Wallpapers"
  '';

  home.activation.protonSyncDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.drive" "$HOME/.config/rclone"
  '';

  systemd.user.services.awww-daemon = {
    Unit = {
      Description = "awww wallpaper daemon";
      PartOf = [ "sway-session.target" ];
      After = [ "sway-session.target" ];
    };
    Service = {
      ExecStart = "${awwwPackage}/bin/awww-daemon";
      Restart = "on-failure";
      RestartSec = 1;
    };
    Install = {
      WantedBy = [ "sway-session.target" ];
    };
  };

  systemd.user.services.proton-rclone-sync = {
    Unit = {
      Description = "Proton Drive rclone bisync";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${protonRcloneSync}/bin/proton-rclone-sync";
      Environment = [
        "HOME=%h"
        "XDG_CONFIG_HOME=%h/.config"
        "XDG_STATE_HOME=%h/.local/state"
        "RCLONE_CONFIG=%h/.config/rclone/rclone.conf"
      ];
    };
  };

  systemd.user.timers.proton-rclone-sync = {
    Unit = {
      Description = "Run Proton Drive rclone bisync regularly";
    };
    Timer = {
      OnBootSec = "5m";
      OnUnitActiveSec = "15m";
      RandomizedDelaySec = "2m";
      Unit = "proton-rclone-sync.service";
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
  };

  programs.swaylock.enable = true;
  programs.rofi =
    let
      inherit (config.lib.formats.rasi) mkLiteral;
    in
    {
      enable = true;
      package = pkgs.rofi;
      font = "JetBrainsMono Nerd Font 13";
      terminal = "ghostty";
      extraConfig = {
        modes = "drun,run,window";
        show-icons = true;
        drun-display-format = "{icon}  {name}";
        display-drun = "Applications";
        display-run = "Run";
        display-window = "Windows";
      };
      theme = {
        "*" = {
          background-color = mkLiteral "#2e3440";
          background-alt = mkLiteral "#3b4252";
          foreground-color = mkLiteral "#eceff4";
          selected-normal-background = mkLiteral "#5e81ac";
          selected-normal-foreground = mkLiteral "#eceff4";
          selected-active-background = mkLiteral "#a3be8c";
          selected-active-foreground = mkLiteral "#2e3440";
          selected-urgent-background = mkLiteral "#bf616a";
          selected-urgent-foreground = mkLiteral "#eceff4";
          border-color = mkLiteral "#88c0d0";
          separatorcolor = mkLiteral "#4c566a";
          urgent-background = mkLiteral "#bf616a";
          urgent-foreground = mkLiteral "#eceff4";
          active-background = mkLiteral "#a3be8c";
          active-foreground = mkLiteral "#2e3440";
        };

        "window" = {
          background-color = mkLiteral "@background-color";
          border = 2;
          border-color = mkLiteral "@border-color";
          border-radius = 10;
          padding = mkLiteral "18px";
          width = mkLiteral "720px";
        };

        "mainbox" = {
          children = map mkLiteral [ "inputbar" "listview" ];
          spacing = mkLiteral "14px";
        };

        "inputbar" = {
          background-color = mkLiteral "@background-alt";
          border-radius = 8;
          children = map mkLiteral [ "prompt" "entry" ];
          padding = mkLiteral "10px 14px";
          spacing = mkLiteral "10px";
        };

        "prompt" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "#88c0d0";
        };

        "entry" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "@foreground-color";
          placeholder = "Search";
          placeholder-color = mkLiteral "#81a1c1";
        };

        "listview" = {
          background-color = mkLiteral "transparent";
          lines = 10;
          columns = 1;
          fixed-height = false;
          spacing = mkLiteral "8px";
          scrollbar = false;
        };

        "element" = {
          background-color = mkLiteral "@background-alt";
          border-radius = 8;
          padding = mkLiteral "10px 12px";
          spacing = mkLiteral "12px";
        };

        "element normal.normal" = {
          background-color = mkLiteral "@background-alt";
          text-color = mkLiteral "@foreground-color";
        };

        "element selected.normal" = {
          background-color = mkLiteral "@selected-normal-background";
          text-color = mkLiteral "@selected-normal-foreground";
        };

        "element-icon" = {
          background-color = mkLiteral "transparent";
          size = mkLiteral "1.2em";
        };

        "element-text" = {
          background-color = mkLiteral "transparent";
          text-color = mkLiteral "inherit";
          vertical-align = mkLiteral "0.5";
        };
      };
    };
  programs.waybar = {
    enable = true;
    settings = [
      {
        layer = "top";
        position = "top";
        modules-left = [ "sway/workspaces" "sway/mode" ];
        modules-center = [ "sway/window" ];
        modules-right = [ "pulseaudio" ] ++ lib.optionals isLaptop [ "backlight" ] ++ [ "network" "battery" "clock" "tray" ];

        "sway/workspaces" = {
          disable-scroll = true;
          all-outputs = true;
          format = "{name}: {icon}";
          format-icons = {
            "1" = "";
            "2" = "";
            "3" = "";
            "4" = "󰎆";
            "5" = "";
            urgent = "";
            default = "";
          };
        };

        clock = {
          format = "{:%a %b %d  %H:%M}";
          tooltip-format = "{:%Y-%m-%d}";
        };

        network = {
          format-wifi = "  {signalStrength}%";
          format-ethernet = "󰈀";
          format-disconnected = "󰖪";
        };

        battery = {
          states = {
            warning = 30;
            critical = 15;
          };
          format = "{icon} {capacity}%";
          format-charging = "󰂄 {capacity}%";
          format-full = "󰁹 {capacity}%";
          format-icons = [ "󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹" ];
          tooltip-format = "{timeTo}";
        };

        pulseaudio = {
          format = "{icon} {volume}%";
          format-muted = "󰖁";
          format-icons = {
            default = [ "󰕿" "󰖀" "󰕾" ];
          };
          on-click = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle";
          on-scroll-up = "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+";
          on-scroll-down = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-";
          tooltip = true;
          tooltip-format = "Left click: mute/unmute\nScroll: adjust volume";
        };

        backlight = {
          format = "{icon} {percent}%";
          format-icons = [ "󰃞" "󰃟" "󰃠" ];
          on-scroll-up = "brightnessctl set 1%+";
          on-scroll-down = "${brightnessDown}/bin/waybar-brightness-down";
          tooltip = true;
          tooltip-format = "Scroll: adjust brightness (min 10%)";
        };
      }
    ];

    style = ''
      * {
        font-family: "JetBrainsMono Nerd Font", "Symbols Nerd Font";
        font-size: 13px;
      }

      window#waybar {
        background: #000000;
        color: #f5f5f5;
        border-bottom: 2px solid #2b2b2b;
      }

      #workspaces {
        margin: 0 8px;
      }

      #workspaces button {
        padding: 0 10px;
        color: #ffb347;
      }

      #workspaces button.focused {
        background: #1f1f1f;
        color: #7dd3fc;
      }

      #window,
      #clock,
      #network,
      #battery,
      #backlight,
      #pulseaudio,
      #tray {
        padding: 0 12px;
      }

      #window {
        color: #f5f5f5;
      }

      #clock {
        color: #c084fc;
      }

      #network {
        color: #34d399;
      }

      #battery {
        color: #facc15;
      }

      #backlight {
        color: #fb7185;
      }

      #pulseaudio {
        color: #60a5fa;
      }

      #tray {
        color: #f97316;
      }
    '';
  };

  services.mako = {
    enable = true;
    settings = {
      background-color = "#2E3440";
      border-color = "#88C0D0";
      text-color = "#ECEFF4";
      default-timeout = 5000;
    };
  };

  services.fusuma = {
    enable = true;
    extraPackages = with pkgs; [ coreutils sway ];
    settings = {
      threshold = {
        swipe = 0.2;
      };
      interval = {
        swipe = 0.8;
      };
      swipe = {
        "3" = {
          left.command = "${pkgs.sway}/bin/swaymsg workspace next_on_output";
          right.command = "${pkgs.sway}/bin/swaymsg workspace prev_on_output";
        };
      };
    };
  };

  services.swayidle = {
    enable = true;
    systemdTarget = "sway-session.target";
    timeouts = [
      {
        timeout = 600;
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
      {
        timeout = 900;
        command = "${pkgs.systemd}/bin/systemctl suspend";
      }
    ];
    events = [
      {
        event = "before-sleep";
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
      {
        event = "lock";
        command = "${pkgs.swaylock}/bin/swaylock -fF";
      }
    ];
  };

}
