#!/usr/bin/env fish

set -l script_dir (status dirname)

exec "$script_dir/toggler.fish" \
    ghostty \
    'title="toggle-ghostty"' \
    -- \
    ghostty \
    --title=toggle-ghostty \
    -e \
    zellij \
    attach \
    --create \
    ghostty
